excluded:
  - Modules/BoxBotCore
  - Pods
  - XcodeTemplates
  - Scripts
  - Examples/BeruServices-Example/Pods
  - Examples/FormKit-Example/Pods
  - Examples/LangExtensionsSample/Pods
  - Examples/MarketCheckoutFeature-Example/Pods
  - Examples/MarketUIExample/Pods
  - Examples/MetricsSample/Pods
  - Examples/UIUtils-Example/Pods

whitelist_rules:
  - anyobject_protocol
  - array_init
  - attributes
  # balanced_xctest_lifecycle
  - block_based_kvo
  # capture_variable 0.43.0 required
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  # comment_spacing 0.42.0 required
  - compiler_protocol_init
  - computed_accessors_order
  # conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  # discouraged_assert 0.43.0 required
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  # explicit_acl
  # explicit_enum_raw_value
  - explicit_init
  # explicit_self
  # explicit_top_level_acl
  # explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  # file_header
  - file_length
  # file_name
  - file_name_no_space
  # file_types_order
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  # function_default_parameter_at_end
  - function_parameter_count
  - generic_type_name
  # ibinspectable_in_extension
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  # inclusive_language
  # indentation_width
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  # legacy_objc_type
  - legacy_random
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  # missing_docs
  - modifier_order
  - multiline_arguments
  # multiline_arguments_brackets
  # multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  # multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  # nimble_operator
  # no_extension_access_modifier
  # no_fallthrough_only
  # no_grouping_extension
  - no_space_in_method_call
  - notification_center_detachment
  - nslocalizedstring_key
  # nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - number_separator
  # object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - optional_enum_case_matching
  - orphaned_doc_comment
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  # prefer_nimble
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  # prefixed_toplevel_constant
  - private_action
  # private_outlet
  - private_over_fileprivate
  # private_subject 0.43.0 required
  - private_unit_test
  # prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  # quick_discouraged_call
  # quick_discouraged_focused_test
  # quick_discouraged_pending_test
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  # required_deinit
  # required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  # sorted_imports
  - statement_position
  - static_operator
  # strict_fileprivate
  # strong_iboutlet
  - superfluous_disable_command
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  # test_case_accessibility
  # todo
  - toggle_bool
  # trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  # type_contents_order
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  # vertical_whitespace_between_cases
  # vertical_whitespace_closing_braces
  # vertical_whitespace_opening_braces
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message
  # yoda_condition

attributes:
  always_on_same_line: ["@IBAction", "@IBOutlet", "@testable", "@objc"]
  always_on_line_above: ["@objcMembers", "@discardableResult"]

closure_body_length: 30

custom_rules:
  no_direct_use_date_formatter:
    name: "Hardcoded DateFormats"
    regex: 'DateFormatter(\.init)?\('
    message: "Use DateFormatter from `DateFormatter+Additions` instead"
    severity: warning

  empty_array_literal:
    name: "Empty array literal"
    regex: "=[\\s]*\\[\\w+\\]\\(\\)"
    message: "Use `: [Type] = []` syntax"
    severity: warning

  empty_dictionary_literal:
    name: "Empty dictonary literal"
    regex: "=[\\s]*\\[\\w+\\: \\w+\\]\\(\\)"
    message: "Use `: [Key: Value] = [:]` syntax"
    severity: warning

  # https://lapcatsoftware.com/articles/fatalError.html
  exclude_fatal_error_usage:
    name: "fatalError() usage isn't allowed"
    message: "Use preconditionFailure or assertionFailure"
    regex: 'fatalError\(.{0,}\)'
    severity: warning

  no_direct_use_of_unique_keys_with_values_initializer:
    name: "Dangerous dictionary initializer"
    regex: '\(\s*uniqueKeysWithValues\s*:\s*.+\)'
    message: "Use init(_:uniquingKeysWith:) instead"
    severity: error

  ns_notification:
    name: "Notification over NSNotification"
    regex: 'NSNotification'
    message: "Prefer Notification over NSNotification"
    severity: warning

  redundant_ternary:
    name: "Redundant ternary"
    regex: ' *? *(?:true|false) *\: *(?:true|false)'
    message: "Don't use a ternary where none is required. E.g. `X ? false : true` can be shortened to just `!X`"
    severity: warning

  swiftgen_assets:
    name: "SwiftGen Assets"
    regex: 'UIImage(\.init)?\(named: ?"?.+"?(, ?in:.+?, ?compatibleWith:.+?)?\)|#imageLiteral\(resourceName: ?".+"\)'
    message: "Use Asset.<asset>.image instead"
    severity: warning

  swiftgen_strings:
    name: "SwiftGen Strings"
    regex: 'NSLocalizedString'
    message: "Use L10n.key instead"
    severity: warning

  use_make_instead_of_create:
    name: "Factory methods naming"
    regex: 'func create'
    message: "Begin names of factory methods with 'make'"
    severity: warning

  wrong_letter:
    name: "Wrong russian or english letter"
    regex: '[а-яА-Я][a-zA-Z]'
    message: "Found cyrillic symbols (cyrillic А instead of English A and etc) or English symbols (English A instead of cyrillic А and etc)."
    severity: warning

  xctassert_fail:
    name: "Use XCTFail"
    regex: '(XCTAssert|XCTAssertTrue)\(false'
    message: "Prefer XCTFail over XCTAssertTrue(false)."
    severity: warning

  xctassert_pass:
    name: "Unnecessary pass"
    regex: '(XCTAssert|XCTAssertTrue)\(true[,)]+'
    message: "Asserting true is unnecessary"
    severity: warning

  xctassert_equal:
    name: "Use XCTAssertEqual"
    regex: '(XCTAssert|XCTAssertTrue)\([^{\n]+? == .+?\)'
    message: "XCTassertEqual will show the value that failed making it easier to debug failing test cases than XCTAssert( == )."
    severity: warning

  # http://dangoldin.com/2019/01/06/javas-simpledateformat-yyyy-vs-yyyy/
  yyyy_date_format:
    name: "YYYYDateFormat"
    regex: 'YYYY'
    message: "Usage of 'YYYY' is usually incorrect. Use 'yyyy' instead."
    severity: error

  file_header_comment:
    name: "File header comment"
    regex: 'DELETE THIS HEADER'
    message: "Delete file header comment"
    severity: warning

  mark_newlines:
    included: ".*.swift"
    name: "MARK newlines surrounding"
    regex: '(([}{)\w \t]+\n{1}[ \t]*)(\/\/ MARK: - [\w ]*))|((\/\/ MARK: - [\w ]*)(\n{1}[ \t]*\w+))'
    message: "Every MARK should be surrounded with 1 newline before and 1 after it"
    severity: warning

cyclomatic_complexity: 15

enum_case_associated_values_count:
  warning: 5
  error: 6

file_length:
  ignore_comment_only_lines: true
  warning: 500

function_body_length: 100

function_parameter_count: 5

identifier_name:
  allowed_symbols: ["_"]
  min_length: 0
  max_length: 40

implicit_return:
  included:
    - closure
    - getter

implicitly_unwrapped_optional:
  mode: all

large_tuple: 3

line_length:
  ignores_comments: true
  warning: 120

modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutators
    - final
    - lazy
    - required
    - convenience
    - typeMethods
    - owned

nesting:
  type_level: 3
  statement_level: 5

type_body_length: 400

type_name:
  min_length: 3
  max_length: 50

unused_declaration:
  include_public_and_open: true
